# Generated by Django 3.1.3 on 2021-11-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=64, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('date', models.DateField()),
                ('duration', models.IntegerField(help_text='Integer in months')),
                ('description', models.TextField()),
                ('keywords', models.ManyToManyField(to='projectsAPI.Keyword')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
