name: Django-Graphne-GraphQL-API CI

on:
  push:
    branches: [ master ]

jobs:
  API_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: pip install -r requirements.txt
      - run: pytest
